const ActionTypes = {
  STORE_VIDEOS: "STORE_VIDEOS",
  APPEND_VIDEOS: "APPEND_VIDEOS",
  SET_REQUEST_DATA: "SET_REQUEST_DATA",
  SET_ACTIVE_VIDEO: "SET_ACTIVE_VIDEO",
};

export default ActionTypes;
